[[ test ]]
game_system = "OnseTool"
input = "3OT>=10"
output = "(3OT>=10) ＞ 13[6,6,1] ＞ クリティカル"
rands = [
  { sides = 6, value = 6 },
  { sides = 6, value = 6 },
  { sides = 6, value = 1 },
]

[[ test ]]
game_system = "OnseTool"
input = "3OT>=10"
output = "(3OT>=10) ＞ 3[1,1,1] ＞ ファンブル"
rands = [
  { sides = 6, value = 1 },
  { sides = 6, value = 1 },
  { sides = 6, value = 1 },
]

[[ test ]]
game_system = "OnseTool"
input = "3OT>=10"
output = "(3OT>=10) ＞ 10[5,1,4] ＞ 成功"
rands = [
  { sides = 6, value = 5 },
  { sides = 6, value = 1 },
  { sides = 6, value = 4 },
]

[[ test ]]
game_system = "OnseTool"
input = "3OT>=10"
output = "(3OT>=10) ＞ 9[5,1,3] ＞ 失敗"
rands = [
  { sides = 6, value = 5 },
  { sides = 6, value = 1 },
  { sides = 6, value = 3 },
]

[[ test ]]
game_system = "OnseTool"
input = "1OT>=3 クリティカルじゃない"
output = "(1OT>=3) ＞ 6[6] ＞ 成功"
rands = [
  { sides = 6, value = 6 },
]

[[ test ]]
game_system = "OnseTool"
input = "1OT>=3"
output = "(1OT>=3) ＞ 1[1] ＞ ファンブル"
rands = [
  { sides = 6, value = 1 },
]

[[ test ]]
game_system = "OnseTool"
input = "TOOLS"
output = "オンセツール決定表(1) ＞ ココフォリア"
rands = [
  { sides = 6, value = 1 },
]
