inherit_from: .rubocop_todo.yml

# Due to old Ruby 1.8.x
Style/Lambda:
  EnforcedStyle: lambda

# Due to old Ruby 1.8.x
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/VariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 6

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Exclude:
    - 'lib/bcdice/game_system/*.rb'

# Due to old Ruby 1.8.x
Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only
